apiVersion: v1
kind: Pod
metadata: 
 name: resources
spec:
  containers:
  - name: nignix
    image: nginx  
    resources:
      requests:
       cpu: "100m"
       memory: "128Mi" # its nothing but 128mb
    limits:
       cpu: "200m"
       memory: "256Mi"