apiVersion: v1
kind: secret
metadata:
  name: secret-basic-auth
data:
  username: c2FpCg==
  password: c2FpMTIzCg==
  ---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    envFrom:
    - secretRef:
        name: secret-course-auth


